SYMBOL_LIST = ['POLUSDT',
              'VETUSDT', 'ETCUSDT', 'TAOUSDT', 'RENDERUSDT', 'FILUSDT', 'FETUSDT', 'ARBUSDT', 'STXUSDT', 'KASUSDT',
              'ALGOUSDT', 'ATOMUSDT', 'AAVEUSDT', 'OMUSDT', 'OMUSDT', 'TIAUSDT', 'XMRUSDT', 'IMXUSDT', 'FTMUSDT',
              'INJUSDT', 'WIFUSDT', '1000BONKUSDT', 'OPUSDT', 'GRTUSDT', 'THETAUSDT', 'SEIUSDT', 'ENAUSDT',
              'WLDUSDT', 'WLDUSDT', 'JASMYUSDT', 'RUNEUSDT', 'ONDOUSDT', '1000FLOKIUSDT', 'SANDUSDT', 'GALAUSDT',
              'EOSUSDT', 'BRETTUSDT', 'KAIAUSDT', 'LDOUSDT', 'LDOUSDT', 'MKRUSDT', 'PYTHUSDT', 'FLOWUSDT',
              'JUPUSDT', 'ARUSDT', 'QNTUSDT', 'IOTAUSDT', 'XTZUSDT', 'BSVUSDT', 'STRKUSDT', 'EGLDUSDT', 'MANAUSDT',
              'NEOUSDT', 'RAYUSDT', 'AXSUSDT', 'APEUSDT', 'ENSUSDT', 'PNUTUSDT']
